### ISSUE TITLE
Suggestion: Allow disabling user registrations

### ISSUE THREAD

**Issue by sbrl** [nicksherron/bashhub-server#17]
**Is your feature request related to a problem? Please describe.**
As a server administrator, I get very nervous if just _anyone_ can register a new account against a service I'm running for personal use.

As a server administrator, I want to prevent new users from creating new accounts, because once I've created an account I don't want to create another one.

**Describe the solution you'd like**
I imagine a solution like a command-line argument such as `--no-registrations` or something. It would completely disable the new user registration system.

**Describe alternatives you've considered**
I've considered running a bashhub-server instance behind a VPN, but this doesn't help me when I'm out and about - and it's cumbersome to setup an entire VPN just to save & retrieve shell history.

I've also considered reverse-proxying bashhub-server and inserting HTTP Basic authentication, but I would guess that this would break the bashhub-client.

**Additional context**
I've like to avoid any potential abuse from people creating spam accounts & filing up the disk / monopolising system resources etc.

**Comment by nicksherron** [comment]
Thanks for the suggestion, it's a good idea and I plan on adding it. I just have to decide on how best to implement it. 

We would probably need to add the ability to create an  "admin" user when starting the server along with a way to generate tokens to place in the `$BH_HOME_DIRECTORY/config` file so that the bashhub client can authenticate and not require the user to run the `bashhub setup` command. If you or anyone else have any thoughts on a clean way to go about this, I'd love to hear them.

**Comment by rcaloras** [comment]
> add the ability to create an "admin" user 

Somewhat related and may help. The jwt token should be able to support whatever params you'd want to add. Not sure your implementation @nicksherron, but you could include a 'role' param to designate as admin.

**Comment by sbrl** [comment]
Thanks!

Roles could be cool, but perhaps the simplest way of doing it would be with a command-line argument perhaps.

Also, does bashhub-server create `.tcb` files in `/tmp`? bashhub-server is the only thing I've changed recently and I logged in to my server today to discover `/tmp` was completely full thereof.
